### ISSUE TITLE
Solution for keeping track of ERC1155 token owners and activity log

### ISSUE THREAD

**Issue by piersss** [airswap/airswap-marketplace#119]
When getting logs from ERC1155 contract you can not filter by tokenId, you have to get the whole history of all the token transfers. So for popular contracts you'll get more than 10000 logs and you'll get this error:

`MetaMask - RPC Error: query returned more than 10000 results. Try with this block range [0xB899C5, 0xC59318].`

@gpxl-dev mentioned this:

> Yes - as the error suggests the parameter you are trying to filter by (_id in the signature above) is not indexed. You can only filer by indexed params.
> 
> So in this case you would need to get all of the transfer events and manually filter them. It sucks, I know...

ERC1155 also lacks a simple function to get the current owner(s) of a token. The only way to get the current owners is by traversing the logs. Please correct me if I'm wrong on this.

**Comment by dmosites** [comment]
Possible to paginate requests by block range? An activity log is nice to have but not critical for MVP if it's blocking.

**Comment by piersss** [comment]
> Possible to paginate requests by block range? An activity log is nice to have but not critical for MVP if it's blocking.

This won't just block the activity log but also the owner(s) info since we need to traverse the whole transaction history.

**Comment by piersss** [comment]
> With this in mind - I am wondering if the rest of the app may have been designed to accomodate this fact (i.e. token/id may not necessarily have one owner in the 1155 case).

I think we're ok on this because orders go by /account/orderNonce. And nft detail page will show the most recent order. Which we have to revise to cheapest because otherwise multiple owners can overwrite each other's orders.
