### ISSUE TITLE
Buyer: See details of an NFT listed for sale

### ISSUE THREAD

**Issue by dmosites** [airswap/airswap-marketplace#12]

**Comment by piersss** [comment]
For MVP we need:
- Price
- Expiry
- Owner
- Proceed to buy button
- Details

**Comment by piersss** [comment]
![Image](https://user-images.githubusercontent.com/86911296/211218204-53968045-0d03-4484-92e7-573f1de61c92.png)
![Image](https://user-images.githubusercontent.com/86911296/211218207-340e9444-1d64-4235-b284-cedd7d769cfe.png)
