### ISSUE TITLE
Mobile Menu

### ISSUE THREAD

**Issue by piersss** [airswap/airswap-marketplace#20]
https://www.figma.com/file/DTJwC2mQ9kvyjM0171tqHR/airswap-web?node-id=13640%3A21079&t=qpsT15RjKpjhmpOy-0

![Image](https://user-images.githubusercontent.com/86911296/210256742-0edfaf98-f40f-47c4-bb1b-38cb7fc75025.png)

Should animate in right to left like airswap-web.

**Comment by 2xAST** [comment]
Please note that the hamburger menu icon changes to an close icon when the menu is opened.
https://www.figma.com/file/DTJwC2mQ9kvyjM0171tqHR/airswap-web?node-id=13707%3A21073&t=TsMba0P9VVp98C6Q-4
