### ISSUE TITLE
Add support for irregular token id numbers

### ISSUE THREAD

**Issue by piersss** [airswap/airswap-marketplace#49]
As discussed here: https://github.com/airswap/airswap-marketplace/issues/22#issuecomment-1379569624

1. Find a token that has irregular numbering (I have not stumbled upon it actually)
2. Add support for it in the .env file by using the example from @gpxl-dev

**Comment by piersss** [comment]
Note: Right now we just hardcoded the increment in `collectionApi`.

**Comment by dmosites** [comment]
Dropped in favor of #62
