### ISSUE TITLE
User profile page

### ISSUE THREAD

**Issue by Goddak** [airswap/airswap-marketplace#63]
**Public profile view (x3)**
![Public Profile](https://user-images.githubusercontent.com/12832288/223965066-4d9ad072-fad2-4747-b9df-03ac218e0163.png)
![Public Profile (1)](https://user-images.githubusercontent.com/12832288/223965072-5b434ffc-034c-4398-b890-81a3d93f5ac8.png)
![Public Profile (2)](https://user-images.githubusercontent.com/12832288/223965081-ee24458d-c8a5-4035-b643-653ceff181a8.png)

**Private profile view (logout button added)**
![Private Profile](https://user-images.githubusercontent.com/12832288/223965173-7b7bc577-f849-4b63-bf99-8e8e4d65fcde.png)

**Comment by GiuntaLucas** [comment]
I guess this issue require the #32 which is the user profile page ?
